/*
 * instructionCodes.h
 *
 *  Created on: 17/7/2016
 *      Author: utnso
 */

#ifndef COMMUNICATIONS_INSTRUCTIONCODES_H_
#define COMMUNICATIONS_INSTRUCTIONCODES_H_

// Configs
#define NUCLEO_PUERTO_ESCUCHA_CONSOLAS "NUCLEO_PUERTO_ESCUCHA_CONSOLAS"
#define NUCLEO_PUERTO_ESCUCHA_CPUS "NUCLEO_PUERTO_ESCUCHA_CPUS"
#define UMC_PUERTO_ESCUCHA "UMC_PUERTO_ESCUCHA"
#define SWAP_PUERTO_ESCUCHA "SWAP_PUERTO_ESCUCHA"

#define CONSOLA_IP "CONSOLA_IP"
#define NUCLEO_IP "NUCLEO_IP"
#define CPU_IP "CPU_IP"
#define UMC_IP "UMC_IP"
#define SWAP_IP "SWAP_IP"

#define LOG_LEVEL "LOG_LEVEL"

// Definiciones de los codigos de handshake para la comunicacion

#define SOY_CONSOLA	101
#define SOY_NUCLEO	102
#define SOY_CPU		103
#define SOY_UMC		104
#define SOY_SWAP	105

//Definiciones entre NUCLEO - CPU
#define FIN_QUANTUM 							200
#define ACTUALIZAR_VARIABLE_COMPARTIDA	 		201
#define WAIT_SEMAFORO 							202
#define SIGNAL_SEMAFORO 						203
#define BLOQUEAR_IO 							204
//#define FIN_PROGRAMA							205
#define ENVIAR_PCB 								206
#define IMPRIMIR_VARIBLE_PANTALLA				207
#define FIN_PROGRAMA_ANSISOP					205
#define OBTENER_VARIABLE_COMPARTIDA 			208
#define IMPRIMIR_TEXTO_PANTALLA					209
#define BLOQUEAR_SEMAFORO						210
#define ERROR_CPU								211

#define PROCESO_BLOQUEADO_WAIT					250
#define PROCESO_NO_BLOQUEADO_WAIT 				251

//Definiciones entre NUCLEO - UMC
#define TAMANIO_PAGINA 						300
#define RESERVAR_PAGINA						301
#define ENVIAR_SCRIPT 						302
#define ELIMINAR_PROGRAMA_DE_MEMORIA		303


#define RESERVAR_PAGINA_OK	350
#define RESERVAR_PAGINA_NO	351

//Definiciones entre NUCLEO - CONSOLA
#define ACEPTO_PROGRAMA		400
#define NO_ACEPTO_PROGRAMA	401

//Definiciones entre UMC - SWAP
#define ESPACIO_SUFICIENTE		500
#define ESPACIO_INSUFICIENTE	501
#define INICIALIZAR_PROGRAMA	502
#define LIBERAR_ESPACIO			503

//Definiciones entre CPU - UMC
#define SOLICITAR_BYTES	600
#define ALMACENAR_BYTES	601
#define CAMBIAR_PROCESO	602
#define DECLARAR_VARIABLE 603

/*Errores*/
#define NO_SE_RECIBIERON_DATOS 0

#endif /* COMMUNICATIONS_INSTRUCTIONCODES_H_ */
